name: CI/CD Pipeline for Streamlit App
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust if your app requires a different version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # For testing, if needed
      - name: Run tests
        run: |
          if [ -d "tests" ]; then pytest tests/ --verbose; else echo "No tests found, skipping"; fi
  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Streamlit Cloud
        run: |
          echo "Pushing to main triggers Streamlit Cloud deployment"
          # No additional steps needed; Streamlit Cloud deploys on push to main 