name: CI/CD Pipeline for Streamlit App
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Streamlit Cloud
        run: |
          echo "Pushing to main triggers Streamlit Cloud deployment"
          # No additional steps needed; Streamlit Cloud deploys on push to main